### PR TITLE
fix #582

### LINKED ISSUE #582: cli "Get started!" code snippet does not compile
# Content Bug Report

## Page(s) Affected
Please list the page or pages this bug is present on. Please file one issue
for each bug you find. Only file an issue for a multi-page bug if the bug is
indeed the *same* bug, across the pages.

https://www.rust-lang.org/what/cli

## What needs to be fixed?
Tell us what content is causing the issue and *how* it is causing the issue.
For example, "The code sample was confusing because it used advanced Rust features",
or "The call to action on the community page was vague".

The type of "num" from struct Cli because the method "take" accepts "usize" as an argument.
"let args = Cli::from_args()?:" should be "let args = Cli::from_args()?;"
Should also add "use structopt::StructOpt;"

## Suggested Improvement
(optional) Do you have a suggestion for how to fix the problem? Include your ideas
here.

Change "num" in struct Cli from "i32" to "usize".
Change "let args = Cli::from_args()?:" to "let args = Cli::from_args()?;"     ":" -> ";"
Add "use structopt::StructOpt;"

### PR DESCRIPTION
**Pull request by andreilorin**
fix typo.
change field type.
add crate.

### CODE REVIEW

**Comment by andreilorin** [comment]
In order for the example code to compile anyone can just copy both snippets into the same file and run them. 
rustc 1.31.0

**Comment by andreilorin** [comment]
This was my first open source pull request... It made me really happy that it got approved !
Thank you!

**Comment by killercup** [comment]
Thanks so much for this! I *just* realized that I forgot to add the structopt import to the code snippet on the website and was about to make a PR -- only to see you already fixed it! <3

**Comment by andreilorin** [comment]
I'm glad I was able to make a small contribution and learn a bit of rust along the way :-)

**Pull request merged**
