### PR TITLE
Recommend using rust-analyzer instead of rls

### PR DESCRIPTION
**Pull request by jrmuizel**
rust-analyzer has a much better experience and is what most people use. No point in leading people astray.

### CODE REVIEW

**Comment by Manishearth** [comment]
There's a tricky thing about rust-analyzer being not-quite-official-yet so we can't recommend it on the website. We're working on it.

**Comment by jrmuizel** [comment]
What's blocking it from being official?

**Comment by Manishearth** [comment]
It's currently developed outside of rust-lang and is not _quite_ run by a rust-lang team. It's not really something that can be helped with externally, we're actively working on pulling it in, there are a couple policy issues that need to be resolved.

**Comment by jrmuizel** [comment]
Would it make sense to just drop the reference to rls in the mean time?

**Comment by Manishearth** [comment]
I don't think so

**Pull request closed without merging**
