### PR TITLE
Fixes #1298 fix not closed divs and add alt

### LINKED ISSUE #1298: Fix DOM not closed html tags
### Page(s) Affected

        modified:   templates/governance/group-team.hbs
        modified:   templates/governance/index.hbs
        modified:   templates/policies/licenses.hbs

### What needs to be fixed?

1. close unclosed Divs
2. Add alt to avatar image of team members

### PR DESCRIPTION
**Pull request by dzhibas**
Fixes #1298

### CODE REVIEW

**Comment by dzhibas** [comment]
@camelid what do you think of this one?  just fixed couple of not closed divs

**Comment by camelid** [comment]
It looks good to me, but I am not a maintainer of this project so you will need a review from someone else.

Please squash your changes here as well with `git rebase -i $(git merge-base master HEAD)` so that it provides a cleaner Git history.

**Comment by camelid** [comment]
By the way, can you add "fixes" before the issue number in this PR as well?

**Comment by AliSajid** [comment]
Hi Rust team. This is really old. Should be easy to merge.

**Comment by senekor** [comment]
Looks good, but there are some conflicts now. I'll merge if they are resolved.

**Comment by dzhibas** [comment]
@senekor iv lost original branch here is new PR with the fixes with up2date master https://github.com/rust-lang/www.rust-lang.org/pull/1299 this PR can be closed in favor of https://github.com/rust-lang/www.rust-lang.org/pull/1299

**Pull request closed without merging**
