### PR TITLE
Fix broken link.

### LINKED ISSUE #1098: [zh-CN] Link report 404
### Page(s) Affected

https://www.rust-lang.org/zh-CN/tools/install

### What needs to be fixed?

....支持 大量平台，....
Link report 404

### PR DESCRIPTION
**Pull request by crlf0710**
I'm not sure whether i should update every locales, or is updating the English one enough?

Closes #1098.

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! If you could also update each locale that would be appreciated.

**Comment by crlf0710** [comment]
Sure~

**Comment by crlf0710** [comment]
Done~

**Comment by XAMPPRocky** [comment]
Thank you again for your PR!

**Pull request merged**
