### PR TITLE
Merge in remaining i18n work

### PR DESCRIPTION
**Pull request by Manishearth**
r? @skade cc @eignnx 

deployed at www-staging.rust-lang.org

### CODE REVIEW

**Comment by skade** [comment]
LGTM. One little question: can we whitelist the locales that are currently deployed/accessible in the main website?

**Comment by Manishearth** [comment]
I'm going to be doing that, but on master

**Comment by Manishearth** [comment]
(That needs to be done in tandem with https://github.com/rust-lang/www.rust-lang.org/pull/815)

**Comment by skade** [comment]
\o/

**Pull request merged**
