### PR TITLE
Fix out of date "Email the Core Team" (and similar) buttons

### LINKED ISSUE #1826: Out of date "Email the Core Team" button on /policies/licenses
The title says it all ^^

Core team is replaced by the new Leadership Council on /governance/teams already, so for consistency, the licenses page needs updating, too.

### PR DESCRIPTION
**Pull request by steffahn**
Fixes #1826

That issue contains all the relevant information, in particular:

> *@steffahn said:*
> Core team is replaced by the new Leadership Council on /governance/teams already, so for consistency, the licenses page needs updating, too.

> *@Manishearth said:*
> would appreciate a PR fixing the English translation, and updating other translations that literally use the phrase "core team". If you list the translations that translated the word "core team" as well I can figure out what to do with them later.

> *@steffahn said:*
> I’ve gone with applying minimal edits to all translations, even the ones that translated "core teams", employing some help from ChatGPT in order to insert the English term "Leadership Council" or "Rust Leadership Council" in the correct place and in a (hopefully) grammatically correct way. Except for Japanese, which I’m a bit familiar with, so I felt it was appropriate to insert a transcription, in a similar style as was done to the term "core team" previously.
>
> I’ll also list the names of the labels that were updated so that any _actual_ translators can feel free to follow-up by inserting a more appropriate native term, at a later point in time, presumably one matching the eventual translation of the new entry on the /governance/teams page.
>
> While I was at it, I’ve also found an instance of a label mentioning "Core Team", on the /production page, where [until 2020](https://github.com/rust-lang/www.rust-lang.org/pull/1037) the "production team" used to be mentioned, but that change never made it into any of the translations, so they kept mentioning a non-existing team (whilst the link was a mailto pointing to the core team).

The relevant translations that need to be adjusted at a later point once translators choose an appropriate term for "Leadership Council" are
* `licenses-license-email-link`
* `policies-reach-out-link`
* `production-share-button`
* `production-contact-core`

*(But perhaps we also might want to change the last key to something like `production-contact-council`.)*

### CODE REVIEW

**Comment by steffahn** [comment]
Two more notes:

* The choice between terms like "Rust Core Team" or "Core Team" used to be somewhat arbitrary, and as a result I somewhat arbitrarily used both "Rust Leadership Council" and "Leadership Council" in this PR, loosely based on whether there used to be a "Rust" next to "Core Team" in many or few of the translations. I’m open to suggestions how this choice can be made more rationally.
* The integration of the English word "Leadership Council" into various languages I’m unfamiliar with using ChatGPT means that while I paid attention to the fact that it _looks like_ all the sentences in all languages remained unchanged except for the replacement of a single term, I did not hand-check in every case that exactly the right words were replaced, not can I be certain that the term "Leadership Council" was inserted in a grammatically correct manner.

For both points, I am of the opinion that this PR is already clearly better compared to the alternatives of turning the whole sentences into English, or compared to leaving incorrect references to (various translations of) "core team" (or worse "production team") in place as-is for an extended time.

**Review by Manishearth — APPROVED** [review]
seems good, the genders also seem correct and if there are mistakes someone will eventually report them

**Comment by Manishearth** [comment]
will show up on https://www-staging.rust-lang.org/ in a bit, once we verify it works we can make a PR from master to deploy

**Comment by steffahn** [comment]
It seems to have appeared on https://www-staging.rust-lang.org/ now indeed ^^

**Pull request merged**
