### PR TITLE
Implementing copy on click install script

### PR DESCRIPTION
**Pull request by haasal**
This PR addresses #1659

I only added the functionality to one of the four (?) code boxes (I'm on Mac).

The code box with `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` will light up on hover and it's content will be copied to the system clipboard on click.

I didn't yet implement the newly added svg because I don't know how svgs are handled in this project. I don't exactly know how to change the fill color of a svg when it is referenced in a template from a file (i.e. when using an img-tag with a svg set as `src`).

It would be great if this small feature would be merged and if you could give me a heads-up if you see something wrong with my edits. Thanks :)

### CODE REVIEW

**Comment by haasal** [comment]
I have found a solution for the svg-problem mentioned in the first comment. This is now ready for review.

**Comment by AliSajid** [comment]
I see that this closes #1659 . Please merge this. It is a minor functional change that will improve User Experience

**Comment by haasal** [comment]
Is there an issue with this PR. If so, please tell me so I can fix it.

**Comment by Manishearth** [comment]
In general the website is in maintenance mode and we basically only make small changes to fix things or changes requested by a team. I plan to figure out a path forward on this, but in the meantime we're not really merging anything complicated. Someone might review this eventually.

**Comment by haasal** [comment]
It has been a long time. Did anything change about the Situation?

**Comment by Manishearth** [comment]
The situation is a bit better but not overly different. @senekor do you want to review this?

**Comment by senekor** [comment]
Not really. I don't think this is worth it. More scattered JS and CSS to maintain while triple-click-ctrl-c works fine. It's not like people come to our site to install Rust multiple times a day.

It's not important for my opinion, but there's a comment saying something about a commercial license for the svg, which is strange.

**Comment by haasal** [comment]
@senekor what do you mean by scattered js? My js is just below all of the other js functions. And what do you mean with the 'commercial license'? The Icon is from Font-Awesome which I Think allows for open-source licensing. If not it is easily replaceable... 

There is a reason why almost every website has a copy button for code boxes

**Comment by senekor** [comment]
I'm not referring to your code quality. I mean scattered as in the query selector for "copyable" class which is added to the code blocks. Ofc this is the right way to do things here, but there's a complexity cost there which I don't think is worth it. Anyway your questions are pushing me to review your code which I said I didn't want to do, so I'll leave it at that.

**Comment by haasal** [comment]
Alright, so this can be closed? Also, do you need maintainers or is there some way to get involved?

**Comment by Manishearth** [comment]
Yeah we'd welcome help reviewing PRs and tweaking things, we're avoiding large changes unless asked by the teams.

**Pull request closed without merging**
