### PR TITLE
Align Items on WASM Getting Started Page

### LINKED ISSUE #604: The Getting started Items of the WASM Page are misaligned
# Content Bug Report

## Page(s) Affected
The [wasm](https://www.rust-lang.org/what/wasm) page

## What needs to be fixed?
There seems to be a miss alignment of the getting started row
image

## Suggested Improvement
Fixing the alignment

### PR DESCRIPTION
**Pull request by Coder206**
Fixes #604 

Before: 
screenshot_2018-12-14 wasm - rust programming language 1

After:
screenshot_2018-12-14 wasm - rust programming language

Inspired by: #623

### CODE REVIEW

**Comment by Coder206** [comment]
I would like to see the text aligned as well but I haven't had any success with using the baseline attributes

**Comment by sondr3** [comment]
I think this SO answer might help: https://stackoverflow.com/a/39197187/273503. This is a bit of a limitation with Flexbox as far as I know, I think this would be fairly easy with CSS Grids (though I really have no idea).

**Comment by Coder206** [comment]
Many thanks @sondr3!

**Comment by r00ster91** [comment]
I think the images should become bigger again as well:
grafik
They are smaller than before.

**Comment by Coder206** [comment]
Thank you for your patience everyone! Let me know what you think :)

**Comment by yoshuawuyts** [comment]
@Coder206 Hmm, this is what it currently looks like on my machine:

## New
2019-01-18-174415_3840x2160

## Old
2019-01-18-174441_3840x2160

I feel this might not be what you were going for with this PR?

**Comment by Coder206** [comment]
Agreed, just to be clear, are we looking to have the images vertically aligned, the first line of the text and the buttons at the same time?

**Comment by yoshuawuyts** [comment]
> Agreed, just to be clear, are we looking to have the images vertically aligned, the first line of the text and the buttons at the same time?

@Coder206 definitely the top of the images and the buttons. I'm less sure about the text -- so probably?

Aligning text might require resizing images, which might take some effort. But if it's possible, perhaps it's worth a shot?

**Comment by skade** [comment]
I think making sure that the images are all the same size is the way to go. @Coder206, is that a change you can do?

**Comment by Coder206** [comment]
@skade I want to make sure I understand, you want me to make the widths of the images the same?

**Comment by skade** [comment]
@Coder206 They should all fit the same box (same height and width), which might need some resizing of the images.

**Comment by skade** [comment]
Fixed by skeleton removal, https://github.com/rust-lang/www.rust-lang.org/issues/830 is a followup.

**Pull request closed without merging**
