### PR TITLE
List support for Visual Studio 2022 on https://www.rust-lang.org/tools #1781

### PR DESCRIPTION
**Pull request by parthopdas**
Adding buttons for VS in https://www.rust-lang.org/tools

### CODE REVIEW

**Comment by Manishearth** [comment]
There are lots of editors with Rust support, we don't want to list all of them (and I'm reluctant to merge this since this adds a new row to the table).

The website has been in a bit of a limbo for a while since there's no official direction for it; there was originally intention for different teams to have decisionmaking power over different parts of the website but that's not currently the case. As such, we rarely if ever change website _content_.

Once the new Rust governance model gets set up I'm hoping to work with the new council to clarify who has direction on which parts of the website, and then maybe such PRs can merge. For now, this PR can stay open if you'd like but I'm not planning on merging it.

**Comment by parthopdas** [comment]
okay. not worth the battle.

there are some misgivings however.
- VS is not "just another editor" - it is "the" editor for windows, vscode has subpar editor / refactoring / testing / debugging experience in comparison
- before the last 3 editors were added there was an incomplete columns - so what if there is a partial row
- if the site is in a limbo and the editor is one of the major ones and the change is simple, not sure what the big deal is to push this through.

**Comment by Manishearth** [comment]
Yes, I understand that it is _the_ editor for Windows. Personally I'd like to _remove_ some of the editors on that list (Geany isn't nearly as popular as it was in the past) and replace them. I haven't done so because of the policy we've been running this on.


> if the site is in a limbo and the editor is one of the major ones and the change is simple, not sure what the big deal is to push this through.

As long as it's in this state the most straightforward rule to follow has been to only merge fixes to things. The moment we start merging more we start having to justify things and deal with people who are annoyed that _their_ change wasn't merged but a _different_ change was. It's a clear line in the sand. Like sure, you can make the argument that it is a major editor to me (and I agree with it), but if I merge this I have to make that same argument to other people who want their editor on the list. I have only committed to keeping the website working, not to maintaining the content; I do not have the time nor the inclination to manage that kind of maintenence. 

It's a bad situation but the website has been in a bad situation for a while, and some other things need to be fixed first. The website is something which a lot of people have strong opinions about but few want to spend time _dealing_ with that, which is why it's come to the state it's in now.

**Comment by Manishearth** [comment]
Actually, you know what? Atom is deprecated and has been for a year.

Go ahead and replace the Atom entry with Visual Studio; and if people argue about it I can point them to this thread.

But for future reference: content changes to the website have no guarantee of being even _considered_.

**Comment by dtolnay** [comment]
> Go ahead and replace the Atom entry with Visual Studio; and if people argue about it I can point them to this thread.

Atom has been deleted as of #1913. I opened #1915 to delete Geany as well, and add Visual Studio.

**Pull request closed without merging**
