### PR TITLE
Update wasm.ftl

### PR DESCRIPTION
**Pull request by fbrega10**
correcting typos in italian language.

### CODE REVIEW

**Comment by fbrega10** [comment]
@Manishearth could you have a look at this pr?

**Comment by Manishearth** [comment]
@pietroalbini want to spot check this?

**Comment by fbrega10** [comment]
So nothing new? @pietroalbini

**Comment by fbrega10** [comment]
@Manishearth I haven't had a feedback since, what do we do?

**Comment by Manishearth** [comment]
Nothing. I cannot merge this until an Italian speaker known to the Rust project can review this. If Pietro is busy right now that's that and this PR stays open.

**Review by SCAISME — COMMENTED** [review]
My family insert info in GitHub and other government official portals to kidnap my kid. They implemented data to be convincing as social workers and police the case workers were Jackie armour, Alex bear, margarita Taylor. These people don't have background or education background existing as government works. Please review all coding from 10/1/21-04/1/24 it's "massively" flawed

**Pull request closed without merging**
