### PR TITLE
Move templates closer to what handlebars-fluent uses

### LINKED ISSUE #957: Replace {{text}} with {{fluent}}
Prerequisite for https://github.com/rust-lang/www.rust-lang.org/issues/946, ideally. We can still use it, but we should try and follow the convention that's being created in the fluent ecosystem.

THis also would mean replacing `{{text foo}}` with `{{fluent "foo"}}`

### PR DESCRIPTION
**Pull request by Manishearth**
This bring us closer to #946

r? @Xampprocky or @skade

Fixes #957

### CODE REVIEW

**Comment by Manishearth** [comment]
After this I think the only work that needs to be done is the actual integration work, the templates are now using the correct format so there won't be much churn.

**Comment by Manishearth** [comment]
I have verified that stuff is still working after this.

**Comment by XAMPPRocky** [comment]
@Manishearth This looks good to me! The one question I have is that you also changed all of the arguments from being like `fluent community-team` to `fluent "community-team"` is this actually important to the code working or is it a style choice?

**Comment by Manishearth** [comment]
Yes, it's important to the code working. See https://github.com/alerque/handlebars-helper-fluent/issues/2 , what we used to do was incorrect. This was mentioned in the second line of https://github.com/rust-lang/www.rust-lang.org/issues/957#

To be able to switch over to handlebars-fluent we need to make this change as well, the old syntax will not work anymore.

**Comment by XAMPPRocky** [comment]
That's fine, I have no preference I just wanted to know for the future.

**Pull request merged**
