### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by dtolnay**
PRs included:

- #1887
- #1892
- #1893
- #1899
- #1904
- #1906
- #1907
- #1908
- #1909
- #1910
- #1913
- #1914
- #1912
- #1915
- #1916
- #1905

Relevant staging links:

- Roles: https://rust-www-staging.herokuapp.com/governance/teams/lang#spec
- Editor support: https://rust-www-staging.herokuapp.com/tools

### CODE REVIEW

**Comment by Manishearth** [comment]
Staging is currently broken, unfortunately. I cannot figure out why, the logs show a succesfull build but Heroku says the build failed.

Not doing a deploy until someone figures out what's going on.

cc @rust-lang/infra

**Comment by dtolnay** [comment]
https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/www.2Erust-lang.2Eorg.20deploy.20is.20failing

> **Jan David Nose:** Heroku lists the last three builds as failed, but has also deployed all three revisions. :raised_eyebrow: 

> **Jan David Nose:** The logs of the failed builds look identical to successful ones.

> **Jan David Nose:** Since I can't find an issue on our side, I've opened a support ticket with Heroku. Will update the thread when I get a response.

**Comment by dtolnay** [comment]
> **Jan David Nose:** It looks to me that the build is timing out. It's running for a *veeery* long time and then gets marked as failed eventually. I've purged the cache and <ins>now the builds succeed again.</ins> ✅ 

https://github.com/rust-lang/www.rust-lang.org/deployments/rust-www-staging

**Comment by Manishearth** [comment]
sweet

**Review by Thompson1985 — APPROVED** [review]

**Review by Thompson1985 — APPROVED** [review]

**Review by Thompson1985 — APPROVED** [review]

**Review by Thompson1985 — APPROVED** [review]

**Review by Thompson1985 — APPROVED** [review]

**Review by Thompson1985 — APPROVED** [review]

**Review by Thompson1985 — APPROVED** [review]

**Pull request merged**
