### PR TITLE
Rocket no longer requires nightly

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by remlse** [comment]
The changes in the README are not enough, rocket actually needs to be updated to a version that doesn't require nightly. the 4.x branch still requires nightly. ~~`0.5.0-rc.2` is the latest version that doesn't.~~ Interestingly, I just tried to update. It doesn't work, rocket `0.5.0-rc.2` apparently still requires nightly..? I'm happy to be corrected. Here's my investigation:

rocket `0.5.0-rc.2` depends on figment 0.10.6, which resolves to 0.10.8 (its latest version). figment in turn pulls in pear 0.2.3. pear makes use of the unstable feature [plugin](https://doc.rust-lang.org/beta/unstable-book/language-features/plugin.html). Both figment and pear are owned by the maintainer of rocket.

That being said, I think now is a good time to switch away from rocket. It has been poorly maintained for years. (Illustrated by how old this PR is and rocket still doesn't have a stable release without requiring nightly.)

Axum and actix-web are both fully featured, much more popular, stable and well-maintained options. I would be glad to help with that.

The `rust-toolchain` file should also be removed, once nightly is not required anymore.

**Comment by Manishearth** [comment]
> It has been poorly maintained for years. (Illustrated by how old this PR is and rocket still doesn't have a stable release without requiring nightly.)



I don't think this is evidence of poor maintenance. Rocket has had an explicit policy of wanting to be an exploration ground for nightly features, and has been a driving force for stabilization in the past.

**Comment by Manishearth** [comment]
I mean, Rocket is fine, it works, it rarely has bugs, it doesn't need to have a constant publish cycle to be considered maintained. It's good enough for us here, are any rate.

It's actively maintained; the stability thing has been taking a while but like I said they've explicitly stated that as a low priority.

**Comment by remlse** [comment]
I need to correct myself: Rocket `0.5` release candidates do compile on stable. It's the `rocket_contrib` dependency that still requires nightly - because it has been [deprecated in `0.5`](https://rocket.rs/master/guide/upgrading-from-0.4/#contrib-deprecation).

In order to upgrade to `0.5`, the templating would have to be migrated to [`rocket_dyn_templates`](https://api.rocket.rs/v0.5-rc/rocket_dyn_templates/index.html).

**Comment by Manishearth** [comment]
Very open to doing that!


(In the long run I'm hoping we can switch to static site generation but we'd need something that can preserve the directory structure)

**Comment by senekor** [comment]
@Manishearth this can be closed as the migration to rocket `0.5` is done.

**Pull request closed without merging**
