### PR TITLE
Replace localization strings for the Learning WG

### LINKED ISSUE #1052: Create a localization string for the rustc-dev-guide WG
### What needs to be fixed?

With the recent rename(s) of the former Learning WG, the `governance-team-wg-learning` localization strings aren't used. Instead, the default name and description defined in rust-lang/team are used for all languages.

### Page(s) Affected

The [compiler team page](https://rust-lang.org/governance/teams/compiler)

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**
Closes #1052

### CODE REVIEW

**Comment by LeSeulArtichaut** [comment]
@pietroalbini Got one more rename for you 😄

**Comment by Manishearth** [comment]
you should rename these strings in all the other localizations too

**Comment by LeSeulArtichaut** [comment]
> you should rename these strings in all the other localizations too
May be a good idea 🙄

**Comment by LeSeulArtichaut** [comment]
@Manishearth Is there a way to reset a particular string for a language? Do I just remove everything after the `=` sign?

**Comment by Manishearth** [comment]
Delete the entry. But do we really need to do that? It seems like the string will still be applicable

**Comment by Manishearth** [comment]
Oh, for the WG name. Yeah just delete the entry

**Comment by LeSeulArtichaut** [comment]
Rebased to resolve conflicts. This should now be ready to merge.

**Comment by XAMPPRocky** [comment]
Thank you for your PR!

**Pull request merged**
