### PR TITLE
Deploy Master Changes

### PR DESCRIPTION
**Pull request by XAMPPRocky**

### CODE REVIEW

**Comment by Manishearth** [comment]
Given that this has two new languages, we should ask the localizers to verify that the staging site is working correctly before merging.

**Comment by Manishearth** [comment]
@vertexclique can you ping the relevant translation teams and ask them to have a look? Not necessarily a super thorough one

**Comment by XAMPPRocky** [comment]
@Manishearth Both of the leads on those translation teams reviewed it earlier today said it looked good.

**Comment by Manishearth** [comment]
Gotcha. Go for it then.

Just a note for future deploys: make sure you cycle through a bunch of pages on the site; the reason the staging site exists is to make sure we don't accidentally break everything.

(Currently the site seems good)

**Comment by XAMPPRocky** [comment]
@Manishearth What makes you think I'm not doing that?

**Comment by Manishearth** [comment]
Nothing, I just wasn't sure if I'd mentioned this earlier and wanted to ensure we're still doing deploys properly.

**Pull request merged**
