### PR TITLE
WIP - improve text legibility (issue #586)

### PR DESCRIPTION
**Pull request by Aloso**
Made red/green background slightly darker, added subtle text shadow for white text.

Related issue: #586

### CODE REVIEW

**Comment by dgriffen** [comment]
I'm not sure where in the CSS it is but you may also want to change the version link color. That only has a contrast ratio of 2.58

**Comment by skade** [comment]
@Aloso I wanted to check in on the progress here. I'd love to have better legibility for those texts, is there anything open to close the associated issue?

**Comment by skade** [comment]
@Aloso ping again :)

**Comment by XAMPPRocky** [comment]
Since this PR has had no activity I'm going to close this. I'm trying to address these issues in #993

**Pull request closed without merging**
