### PR TITLE
Improve the Sponsors page and add 1Password to it

### PR DESCRIPTION
**Pull request by pietroalbini**
This PR makes a few changes to the sponsors page:

* The page is now generated dynamically from the data in `src/data/sponsors.yml`, and the order in which the sponsors are displayed changes every time the page is visited.
* The logos are now SVGs instead of PNGs, as they scale better depending on the display size and are generally smaller. I needed to add a custom CSP policy to display SVGs properly.
* Added 1Password as a sponsor of the project, as they recently started providing a free 1Password Teams subscription (see https://github.com/1Password/1password-teams-open-source/pull/172). Along with that I removed the section about sponsoring our 1Password account from Mozilla.
* Tweaked the styling a little bit.

**Preview of the changes:**

Screenshot_2019-12-10 Sponsors(1)

### CODE REVIEW

**Comment by pietroalbini** [comment]
@oliverdunk (from 1Password), :wave:

We're working on a sponsors page for the Rust project (not yet deployed to production), and as 1Password is now sponsoring our subscription we should add the company to it. Is this small description of what you're providing good on your end?

> 1Password is providing a free 1Password Teams subscription to the Rust Team, used to store and share secrets between team members.

**Comment by oliverdunk** [comment]
> @oliverdunk (from 1Password), 👋
> 
> We're working on a sponsors page for the Rust project (not yet deployed to production), and as 1Password is now sponsoring our subscription we should add the company to it. Is this small description of what you're providing good on your end?
> 
> > 1Password is providing a free 1Password Teams subscription to the Rust Team, used to store and share secrets between team members.

Hey @pietroalbini! Thanks for looping me in here and checking the wording. It sounds perfect :)

Will be very proud to see our logo there. Thanks for adding us!

**Comment by oliverdunk** [comment]
Hi again @pietroalbini 👋

Just curious if this live at the moment? I'm super excited to share it with the team, and wasn't sure if I was just missing the URL. No worries if not.

**Comment by pietroalbini** [comment]
@oliverdunk this is live on our staging server: https://rust-www-staging.herokuapp.com/sponsors
Opened a PR to deploy it to production: https://github.com/rust-lang/www.rust-lang.org/pull/967

**Pull request merged**
