### PR TITLE
Deploy French translation

### PR DESCRIPTION
**Pull request by gitsignore**
Enabled French translations.

@rust-lang-owner

### CODE REVIEW

**Comment by Manishearth** [comment]
Has this been approved by the translation team?

@phaazon

**Comment by phaazon** [comment]
We were left with some questions about two words. Ping @nightmared.

To me, it should be okay to release, as 99,9% of the work is done, reviewed and okay. The remaining words (two) are nit-picking that we can resolve later, as both suggestions are okay.

**Comment by nightmared** [comment]
I concur with @phaazon, this looks all right to me.

**Comment by Manishearth** [comment]
Alright, please check out https://www-staging.rust-lang.org/fr  and ensure stuff is working right!

**Pull request merged**
