### PR TITLE
Use different purple

### PR DESCRIPTION
**Pull request by XAMPPRocky**
This updates the colour scheme based on talking with @pietroalbini to use a purple that is more deep blue.

- **Try It Out** — https://www-try.rust-lang.org
- **Staging** — https://www-staging.rust-lang.org
- **Production** — https://www.rust-lang.org

### New / Production

Screenshot 2020-03-01 at 14 09 58

### New / Master

Screenshot 2020-03-01 at 14 10 18

### CODE REVIEW

**Comment by pietroalbini** [comment]
I'd slightly prefer a saturation of 30% / 35%, but this looks way better to me! @Manishearth

**Comment by XAMPPRocky** [comment]
Here's a screenshot of 30%, personally I don't like it as it looks too gray compared to the new purple.

### New / 30% Saturation

Screenshot 2020-03-01 at 20 49 50

**Comment by pietroalbini** [comment]
The color introduced in the PR is starting to grow on me! Let's wait for @Manishearth's approval and then we can merge this.

By the way, I chatted with Erin and it turns out there was a miscommunication, the color with 30% saturation I was proposing is `#312a4f`.

**Comment by Manishearth** [comment]
Yeah, this looks way better to me as well (and my understanding is that in the poll about colors people liked the new green but not the new-now-old purple)

**Pull request merged**
