### PR TITLE
Localize Privacy Notice

### LINKED ISSUE #1034: Localize privacy policy
### What needs to be fixed?
The Privacy Policy page is not localizable.

### Page(s) Affected
https://www.rust-lang.org/es/policies/privacy

### Suggested Improvement
We should move the content to a fluent file. I have a PR ready!

### PR DESCRIPTION
**Pull request by jrvidal**
Fixes #1034

### CODE REVIEW

**Comment by Manishearth** [comment]
Thanks! Once this gets deployed to www-staging.rust-lang.org/ I'll have a closer look to see if there are any differences.

**Comment by XAMPPRocky** [comment]
@Manishearth Should we have something at the top saying the english version is the canonical version like people have suggested for other policies?

**Comment by Manishearth** [comment]
Oh, yes, definitely. Good catch

**Comment by Manishearth** [comment]
The content hasn't changed :+1: We're good to go for translating it, though we should still add that header.

**Comment by upsuper** [comment]
Hey! Just noticed this new string now. Can we avoid put large chunk of HTML like `policies-privacy-page-crates-io-desc` into text piece? Pontoon's UI is not particularly optimized for large chunk of text like this. It's hard to translate (you have to translate all in one go or nothing), hard to review (you have to manually scroll original and translation), hard to distribute the work (again, you have to do them altogether), hard to update (you can't reuse anything from previous translation even if only minor changes are done to the text).

It would be appreciated if this kind of text can be broken down to just one item a string instead, e.g. rather than having `<dl><dt>` all in `ftl` file, keep the structure in the template.

WDYT?

**Pull request merged**
