### PR TITLE
Update learn-rustlings link

### PR DESCRIPTION
**Pull request by 4i8**
**Update rustlings link to [rustlings](https://rustlings.cool/) for a better user experience**

### CODE REVIEW

**Comment by Manishearth** [comment]
cc @rust-lang/infra is rustlings.cool managed by us? It is linked to on the rustlings git repo.

**Comment by 4i8** [comment]
> cc @rust-lang/infra is rustlings.cool managed by us? It is linked to on the rustlings git repo.

Yes it's managed by rust team
image

**Comment by Manishearth** [comment]
I understand that, the question is if the _domain_ is managed by the _Rust infra team_. This is distinct from the domain being controlled by a Rust subteam.

**Comment by jdno** [comment]
Sorry for the late reply. This got lost in my GitHub notifications.

The short answer is that the infra-team does not own or manage the domain.

While only tangentially related to the website, I've [started a discussion in #t-infra on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Domains.20on.20GitHub) on how we want to handle URLs on GitHub repos. From a security perspective, it would be better if the infra-team owns the domains that we link to from GitHub or that are associated with projects on the website. And it seems also fairer if we cover the costs of these domains.

**Comment by 4i8** [comment]
No problem at all! Thanks for letting me know.

**Comment by 4i8** [comment]
> Sorry for the late reply. This got lost in my GitHub notifications.
> 
> The short answer is that the infra-team does not own or manage the domain.
> 
> While only tangentially related to the website, I've [started a discussion in #t-infra on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Domains.20on.20GitHub) on how we want to handle URLs on GitHub repos. From a security perspective, it would be better if the infra-team owns the domains that we link to from GitHub or that are associated with projects on the website. And it seems also fairer if we cover the costs of these domains.

No problem at all! Thanks for letting me know.

**Pull request closed without merging**
