### PR TITLE
Remove TenX from production users

### LINKED ISSUE #2005: Defunct company (TenX) listed as productive user
### What needs to be fixed?
TenX is still listed as an active user. The company is defunct. The link to their website is down anyhow.

### Page(s) Affected
https://www.rust-lang.org/production/users

### Suggested Improvement
Remove TenX from that site.

### PR DESCRIPTION
**Pull request by senekor**
closes #2005

### CODE REVIEW

**Comment by senekor** [comment]
@Manishearth what's your opinion on removing this page entirely? Is that too significant of a content change? Should we wait for a more clear governance of the website & broader consensus?

**Comment by Manishearth** [comment]
I think at this stage tbh I'd go ahead and just remove the thing. We're not maintaining it particularly well and I don't think the broader governance would allocate this page to anyone but the website team.

**Review by Manishearth — APPROVED** [review]
still feel free to merge, i think it's your call

**Comment by senekor** [comment]
superseded by #2010

**Pull request closed without merging**
