### PR TITLE
Remove horizontal rule from "Generating a new project" on "Getting started" page

### PR DESCRIPTION
**Pull request by camelid**
It looks out of place and a bit weird in this spot to me.

@rustbot modify labels: A-Design

### CODE REVIEW

**Comment by camelid** [comment]
# Before

image

# After

image

**Comment by Manishearth** [comment]
It seems fine to me, it's being separated into two logical steps. Otherwise it kinda looks like a list of `cargo` things with the `cargo run` not having any text with it, which is confusing

**Comment by camelid** [comment]
Okay, would it be okay if I changed the color of the rule to white to match the text? I think the gray against the red just looks weird to me.

**Comment by Manishearth** [comment]
Yes

**Comment by senekor** [comment]
superseded by https://github.com/rust-lang/www.rust-lang.org/pull/1966

**Pull request closed without merging**
