### PR TITLE
Enable triagebot

### PR DESCRIPTION
**Pull request by camelid**
r? @XAMPPRocky

### CODE REVIEW

**Comment by camelid** [comment]
I just copied over part of the rust-lang/rust `triagebot.toml` file, so I'm not sure if this is what we want.

**Comment by camelid** [comment]
@XAMPPRocky could you take a look at this? Thanks!

**Comment by XAMPPRocky** [comment]
Sorry fell off my queue,  I need to go through the triagebot documentation on forge and I'll merge this sometime soon.

**Comment by camelid** [comment]
Sure!

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Comment by camelid** [comment]
Thanks!

**Pull request merged**
