### PR TITLE
Remove stale community page content

### LINKED ISSUE #1720: Community page lists 2020 events
### What needs to be fixed?
Content on events and happenings in the community is quite stale :grimacing: 

### Page(s) Affected
https://www.rust-lang.org/community

### Suggested Improvement
- Have someone own that this page is updated regularly
- (less ideal) remove explicitly dated materials that are likely to become stale

### PR DESCRIPTION
**Pull request by senekor**
closes #1720

<details>
<summary>before</summary>

</details>

<details>
<summary>after</summary>

</details>

### CODE REVIEW

**Comment by senekor** [comment]
Still a draft because I see two open questions:
- [ ] Is the "register your event" google form still active / relevant?
- [ ] The "view calendar" link doesn't seem completely dead, but would it be better to link to "This Week in Rust" instead? If so, can we automatically link to its latest issue?

**Comment by senekor** [comment]
also closes #1902

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
cc @badboy can you answer the two questions above?

**Comment by badboy** [comment]
Sorry, I had this open and then forget to reply.

> Still a draft because I see two open questions:
> 
>     * [x]  Is the "register your event" google form still active / relevant?
>       -> Nobody answered saying it's stale, so we should assume it's not and keep it as is.

No one's looking at that, so +1 on the removal.

>     * [x]  The "view calendar" link doesn't seem completely dead, but would it be better to link to "This Week in Rust" instead? If so, can we automatically link to its latest issue? ([Link to latest issue? this-week-in-rust#5544](https://github.com/rust-lang/this-week-in-rust/issues/5544))
>       -> We cannot link directly to the "upcoming events" section of the latest TWiR issue and it seems hard to implement. Leaving the current link to the google calendar seems fine though, since it's actually the [source for TWiR](https://github.com/rust-lang/this-week-in-rust/blob/master/docs/assembling_twir.md?rgh-link-date=2024-05-23T18%3A10%3A22Z#events).

Indeed that calendar is still the source of truth, so I'd say it's ok to leave it in.

**Comment by senekor** [comment]
> No one's looking at that, so +1 on the removal.

Where else should people register their events / get in touch with the events team? The text of that section doesn't make much sense without any link at all.

**Comment by badboy** [comment]
> > No one's looking at that, so +1 on the removal.
> 
> Where else should people register their events / get in touch with the events team? The text of that section doesn't make much sense without any link at all.

There's not much of an event team anymore, but a mail to community@ is still the way to go.

**Comment by senekor** [comment]
Alright, I replaced it with the same email link as the one in the above section.

<details>
<summary>preview</summary>

</details>

**Pull request merged**
