### PR TITLE
#1292 sponsors description might have html no escape

### PR DESCRIPTION
**Pull request by dzhibas**
disables sponsors description escaping, to properly render spanish html tags in some sponsors

### CODE REVIEW

**Comment by dzhibas** [comment]
choose one of 2 solutions:
https://github.com/rust-lang/www.rust-lang.org/pull/1295
https://github.com/rust-lang/www.rust-lang.org/pull/1294

the other one close

**Comment by camelid** [comment]
I believe this is the correct solution and the other PR should be closed.

Could you [squash your commits](https://rustc-dev-guide.rust-lang.org/git.html#advanced-rebasing)?

**Comment by dzhibas** [comment]
@camelid  here is another PR with just that changeset https://github.com/rust-lang/www.rust-lang.org/pull/1301

**Comment by dzhibas** [comment]
this can be closed if another taken

**Comment by camelid** [comment]
Okay, do you want to close this one in favor of #1301?

**Comment by dzhibas** [comment]
Yes please, lets close this one in favor of cleaner #1301

**Pull request closed without merging**
