### PR TITLE
Remove skeleton

### PR DESCRIPTION
**Pull request by skade**
Kills the last 2 mentions of skeleton classes, removes the CSS file.

I went through all pages, but please do so again on review.

### CODE REVIEW

**Comment by pietroalbini** [comment]
Can someone else review this? I'm pretty filled with other stuff right now.

**Comment by Mark-Simulacrum** [comment]
A quick grep for skeleton finds some `button-secondary--no-skeleton` classes and such in the code which should probably be removed along with skeleton in this PR:

```
templates/learn/index.hbs
50:{{!-- TODO: Remove button-secondary--no-skeleton once Skeleton is completely removed. --}}
55:             class="button button-secondary button-secondary--no-skeleton mw6-l w-100">{{text learn-doc-std-button}}</a>
63:             class="button button-secondary button-secondary--no-skeleton mw6-l w-100">{{text learn-doc-edition-button}}</a>
71:             class="button button-secondary button-secondary--no-skeleton mw6-l w-100">{{text learn-doc-cargo-button}}</a>
79:             class="button button-secondary button-secondary--no-skeleton mw6-l w-100">{{text learn-doc-rustdoc-button}}</a>
87:             class="button button-secondary button-secondary--no-skeleton mw6-l w-100">{{text learn-doc-rustc-button}}</a>
95:             class="button button-secondary button-secondary--no-skeleton mw6-l w-100">{{text learn-doc-error-button}}</a>
108:               class="button button-secondary button-secondary--no-skeleton mw6-l w-100">
118:               class="button button-secondary button-secondary--no-skeleton mw6-l w-100">
128:               class="button button-secondary button-secondary--no-skeleton mw6-l w-100">

src/styles/app.scss
113:.button.button-secondary--no-skeleton {
```

**Comment by skade** [comment]
@Mark-Simulacrum right, thank you

**Comment by skade** [comment]
@Mark-Simulacrum It's been a while. Updated.

**Comment by Mark-Simulacrum** [comment]
r=me with Skeleton removed from CONTRIBUTING.md as well

**Comment by pBeta00n** [comment]
https://github.com/rust-lang/www.rust-lang.org/pull/833#issuecomment-516114871

**Comment by skade** [comment]
Removed from contributing, merging when checks are green.

**Pull request merged**
