### PR TITLE
Add sponsors page

### PR DESCRIPTION
**Pull request by carols10cents**
This adds a section to the bottom of the homepage for thanks in general, with links to thanks.rust-lang.org and a new sponsors page:

new homepage section

The new sponsors page thanks Microsoft, AWS, and Mozilla for their infrastructure sponsorships (in 2 screenshots, there isn't actually a blank spot on the page between Microsoft and AWS):

new sponsors page part 1

new sponsors page part 2

I took most of the text from [the 1.37.0 release announcement](https://blog.rust-lang.org/2019/08/15/Rust-1.37.0.html#new-sponsors-of-rust-infrastructure).

Before merging this, I would like review on the text and logo inclusion from:

- [ ] @nikomatsakis for Mozilla
- [x] @alexcrichton to contact AWS and get their approval
- [x] @rylev for Microsoft

I'm happy to make any modifications; let me know what needs to change. Thanks!

### CODE REVIEW

**Comment by skade** [comment]
I think the approach of putting a thanks on the homepage is a very clever one, thanks!

**Comment by pietroalbini** [comment]
cc @davidbarsky for the AWS side.

By the way, maybe the page order should be randomized like we do for [the production users page](https://www.rust-lang.org/production/users)?

**Comment by davidbarsky** [comment]
This looks great! I think the randomization would be a good addition.

**Comment by skade** [comment]
I have a concern here: are we free to translate those texts or do any of the sponsors feel like they must approve translations? Or am I overthinking this?

**Comment by pietroalbini** [comment]
Mozilla is also providing a dedicated server for perf btw.

**Comment by davidbarsky** [comment]
At least from AWS' side, I think y'all should be free to translate those texts without AWS' approval. It's a decently small blurb, and so long the intent is carried over, then I don't think there will be any issue.

**Comment by rylev** [comment]
I'm triple checking with marketing about this, but it looks great to me. I don't believe there are any issues that would require approval of translations.

**Comment by skade** [comment]
Thanks @davidbarsky and @rylev!

**Comment by rylev** [comment]
This should be fine from our end! Thanks for the shout out!

**Comment by skade** [comment]
Merging this to staging, please wait for sign-off from @nikomatsakis

**Comment by nikomatsakis** [comment]
Just to be clear, I did sign off (cc @skade)

**Pull request merged**
