### PR TITLE
Add dark + light svg versions of rust-social-wide

### LINKED ISSUE #1943: Dark + Light SVG versions of rust-social-wide.jpg
### Summary
Add an SVG version of [/static/images/rust-social-wide.jpg](../tree/master/static/images/rust-social-wide.jpg) with dark and light variants.

### Motivation
For use in https://github.com/rust-lang/rust/pull/123093

### Rationale and alternatives
Alternatively, these SVGs could be added directly to the `rust-lang/rust` repo where they would be used.

### PR DESCRIPTION
**Pull request by onefifth**
Matched the font ([Fria Sans](https://fonts.google.com/specimen/Fira+Sans)) from the existing rust-social-wide.jpg

These icons are intended for use in the rust-lang GitHub readme via https://github.com/rust-lang/rust/pull/123093

Closes #1943

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
Seems useful for the rust project.

**Comment by Urgau** [comment]
@onefifth I don't think it's intended but on my system the text is not rendered properly (the font is not right and the text is cut off).

image

**Comment by onefifth** [comment]
@Urgau Huh weird! I was matching the way the esbuild SVG logo you'd referenced handled text.

I'll take a look and update with a converted to path version in a few hours. 

My readme pull request won't need updating as the SVG URLs in the readme won't change.

**Comment by Urgau** [comment]
Inspired by our attempt to make it a SVG. I took a stab at it. That's what I got, it's not perfect but I think it's a good start.

7pndz1prpjblujki9kt

I used the official blank Rust logo: https://github.com/rust-lang/rust-artwork/blob/master/logo/rust-logo-blk.svg
And the [Google Font to Svg Path](https://danmarshall.github.io/google-font-to-svg-path/) project to create the text outlines.

<details>

screenshot

</details>

**Comment by onefifth** [comment]
Opened a new issue https://github.com/rust-lang/www.rust-lang.org/issues/1946 and matching PR https://github.com/rust-lang/www.rust-lang.org/pull/1947 with updated SVGs

**Pull request merged**
