### PR TITLE
Add Gandi to the list of sponsors

### PR DESCRIPTION
**Pull request by pietroalbini**
This PR adds [Gandi](https://www.gandi.net) to the sponsors page. We need to get back from them to approve the wording.

Screenshot_2019-12-16 Sponsors

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@pietroalbini great; have they approved the wording?

**Comment by pietroalbini** [comment]
Yeah, I'll merge this when we get the sponsored account.

**Comment by XAMPPRocky** [comment]
@pietroalbini Can we merge this now?

**Comment by pietroalbini** [comment]
@XAMPPRocky we're still finalizing the sponsorship, I'll merge the PR once we're ok on that front.

**Comment by AliSajid** [comment]
Rust Team, please check back and merge this.

**Comment by pietroalbini** [comment]
Not relevant anymore.

**Pull request closed without merging**
